## Exploring the xarray library

In [1]:
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt

In [2]:
ds = xr.tutorial.load_dataset("air_temperature")
ds

<xarray.Dataset>
Dimensions:  (lat: 25, time: 2920, lon: 53)
Coordinates:
  * lat      (lat) float32 75.0 72.5 70.0 67.5 65.0 ... 25.0 22.5 20.0 17.5 15.0
  * lon      (lon) float32 200.0 202.5 205.0 207.5 ... 322.5 325.0 327.5 330.0
  * time     (time) datetime64[ns] 2013-01-01 ... 2014-12-31T18:00:00
Data variables:
    air      (time, lat, lon) float32 241.2 242.5 243.5 ... 296.5 296.2 295.7
Attributes:
    Conventions:  COARDS
    title:        4x daily NMC reanalysis (1948)
    description:  Data is from NMC initialized reanalysis\n(4x/day).  These a...
    platform:     Model
    references:   http://www.esrl.noaa.gov/psd/data/gridded/data.ncep.reanaly...

#### What’s in a Dataset? *Many DataArrays!*

In [3]:
ds.air

<xarray.DataArray 'air' (time: 2920, lat: 25, lon: 53)>
array([[[241.2    , 242.5    , 243.5    , ..., 232.79999, 235.5    ,
         238.59999],
        [243.79999, 244.5    , 244.7    , ..., 232.79999, 235.29999,
         239.29999],
        [250.     , 249.79999, 248.89   , ..., 233.2    , 236.39   ,
         241.7    ],
        ...,
        [296.6    , 296.19998, 296.4    , ..., 295.4    , 295.1    ,
         294.69998],
        [295.9    , 296.19998, 296.79   , ..., 295.9    , 295.9    ,
         295.19998],
        [296.29   , 296.79   , 297.1    , ..., 296.9    , 296.79   ,
         296.6    ]],

       [[242.09999, 242.7    , 243.09999, ..., 232.     , 233.59999,
         235.79999],
        [243.59999, 244.09999, 244.2    , ..., 231.     , 232.5    ,
         235.7    ],
        [253.2    , 252.89   , 252.09999, ..., 230.79999, 233.39   ,
         238.5    ],
...
        [293.69   , 293.88998, 295.38998, ..., 295.09   , 294.69   ,
         294.29   ],
        [296.29   , 297.19   , 297.59   , ..., 295.29   , 295.09   ,
         294.38998],
        [297.79   , 298.38998, 298.49   , ..., 295.69   , 295.49   ,
         295.19   ]],

       [[245.09   , 244.29   , 243.29   , ..., 241.68999, 241.48999,
         241.79   ],
        [249.89   , 249.29   , 248.39   , ..., 239.59   , 240.29   ,
         241.68999],
        [262.99   , 262.19   , 261.38998, ..., 239.89   , 242.59   ,
         246.29   ],
        ...,
        [293.79   , 293.69   , 295.09   , ..., 295.29   , 295.09   ,
         294.69   ],
        [296.09   , 296.88998, 297.19   , ..., 295.69   , 295.69   ,
         295.19   ],
        [297.69   , 298.09   , 298.09   , ..., 296.49   , 296.19   ,
         295.69   ]]], dtype=float32)
Coordinates:
  * lat      (lat) float32 75.0 72.5 70.0 67.5 65.0 ... 25.0 22.5 20.0 17.5 15.0
  * lon      (lon) float32 200.0 202.5 205.0 207.5 ... 322.5 325.0 327.5 330.0
  * time     (time) datetime64[ns] 2013-01-01 ... 2014-12-31T18:00:00
Attributes:
    long_name:     4xDaily Air temperature at sigma level 995
    units:         degK
    precision:     2
    GRIB_id:       11
    GRIB_name:     TMP
    var_desc:      Air temperature
    dataset:       NMC Reanalysis
    level_desc:    Surface
    statistic:     Individual Obs
    parent_stat:   Other
    actual_range:  [185.16 322.1 ]

#### What’s in a DataArray? *data + (a lot of) metadata*

`.dims` correspond to the axes of your data. That is, your multi-dimensioal data has a name for each axis (which is quite nice!)

In [4]:
ds.air.dims

('time', 'lat', 'lon')

`.coords` is a simple data container for coordinate variables. This contains the actual values of the dims (or axes). For instance, we have a vector and we know that each point corresponds to a single time point. Well, the axes in this case would be time, but the actual values of the timepoints are stored in the `coords`.

In [5]:
ds.air.coords

Coordinates:
  * lat      (lat) float32 75.0 72.5 70.0 67.5 65.0 ... 25.0 22.5 20.0 17.5 15.0
  * lon      (lon) float32 200.0 202.5 205.0 207.5 ... 322.5 325.0 327.5 330.0
  * time     (time) datetime64[ns] 2013-01-01 ... 2014-12-31T18:00:00

#### How to get access to the values of a single coordinate/axes?

In [6]:
ds.air.lat

<xarray.DataArray 'lat' (lat: 25)>
array([75. , 72.5, 70. , 67.5, 65. , 62.5, 60. , 57.5, 55. , 52.5, 50. , 47.5,
       45. , 42.5, 40. , 37.5, 35. , 32.5, 30. , 27.5, 25. , 22.5, 20. , 17.5,
       15. ], dtype=float32)
Coordinates:
  * lat      (lat) float32 75.0 72.5 70.0 67.5 65.0 ... 25.0 22.5 20.0 17.5 15.0
Attributes:
    standard_name:  latitude
    long_name:      Latitude
    units:          degrees_north
    axis:           Y

In [7]:
ds.air.coords.variables["lat"]

<xarray.IndexVariable 'lat' (lat: 25)>
array([75. , 72.5, 70. , 67.5, 65. , 62.5, 60. , 57.5, 55. , 52.5, 50. , 47.5,
       45. , 42.5, 40. , 37.5, 35. , 32.5, 30. , 27.5, 25. , 22.5, 20. , 17.5,
       15. ], dtype=float32)
Attributes:
    standard_name:  latitude
    long_name:      Latitude
    units:          degrees_north
    axis:           Y

In [8]:
ds.air.lat.values

array([75. , 72.5, 70. , 67.5, 65. , 62.5, 60. , 57.5, 55. , 52.5, 50. ,
       47.5, 45. , 42.5, 40. , 37.5, 35. , 32.5, 30. , 27.5, 25. , 22.5,
       20. , 17.5, 15. ], dtype=float32)

In [9]:
ds.air.time.values

array(['2013-01-01T00:00:00.000000000', '2013-01-01T06:00:00.000000000',
       '2013-01-01T12:00:00.000000000', ...,
       '2014-12-31T06:00:00.000000000', '2014-12-31T12:00:00.000000000',
       '2014-12-31T18:00:00.000000000'], dtype='datetime64[ns]')

In [10]:
ds.air.time.data

array(['2013-01-01T00:00:00.000000000', '2013-01-01T06:00:00.000000000',
       '2013-01-01T12:00:00.000000000', ...,
       '2014-12-31T06:00:00.000000000', '2014-12-31T12:00:00.000000000',
       '2014-12-31T18:00:00.000000000'], dtype='datetime64[ns]')

#### Sanity check: the length of each coordinate should correspond to the length of the dimensions in our original data

In [11]:
ds.air.shape

(2920, 25, 53)

In [12]:
for coord_name in ds.air.dims:
    print(coord_name, ds.air.coords.variables[coord_name].shape)

time (2920,)
lat (25,)
lon (53,)


`.attrs` is a dictionary that can contain arbitrary Python objects (strings, lists, integers, dictionaries, etc.) Your only limitation is that some attributes may not be writeable to certain file formats.

In [13]:
ds.air

<xarray.DataArray 'air' (time: 2920, lat: 25, lon: 53)>
array([[[241.2    , 242.5    , 243.5    , ..., 232.79999, 235.5    ,
         238.59999],
        [243.79999, 244.5    , 244.7    , ..., 232.79999, 235.29999,
         239.29999],
        [250.     , 249.79999, 248.89   , ..., 233.2    , 236.39   ,
         241.7    ],
        ...,
        [296.6    , 296.19998, 296.4    , ..., 295.4    , 295.1    ,
         294.69998],
        [295.9    , 296.19998, 296.79   , ..., 295.9    , 295.9    ,
         295.19998],
        [296.29   , 296.79   , 297.1    , ..., 296.9    , 296.79   ,
         296.6    ]],

       [[242.09999, 242.7    , 243.09999, ..., 232.     , 233.59999,
         235.79999],
        [243.59999, 244.09999, 244.2    , ..., 231.     , 232.5    ,
         235.7    ],
        [253.2    , 252.89   , 252.09999, ..., 230.79999, 233.39   ,
         238.5    ],
...
        [293.69   , 293.88998, 295.38998, ..., 295.09   , 294.69   ,
         294.29   ],
        [296.29   , 297.19   , 297.59   , ..., 295.29   , 295.09   ,
         294.38998],
        [297.79   , 298.38998, 298.49   , ..., 295.69   , 295.49   ,
         295.19   ]],

       [[245.09   , 244.29   , 243.29   , ..., 241.68999, 241.48999,
         241.79   ],
        [249.89   , 249.29   , 248.39   , ..., 239.59   , 240.29   ,
         241.68999],
        [262.99   , 262.19   , 261.38998, ..., 239.89   , 242.59   ,
         246.29   ],
        ...,
        [293.79   , 293.69   , 295.09   , ..., 295.29   , 295.09   ,
         294.69   ],
        [296.09   , 296.88998, 297.19   , ..., 295.69   , 295.69   ,
         295.19   ],
        [297.69   , 298.09   , 298.09   , ..., 296.49   , 296.19   ,
         295.69   ]]], dtype=float32)
Coordinates:
  * lat      (lat) float32 75.0 72.5 70.0 67.5 65.0 ... 25.0 22.5 20.0 17.5 15.0
  * lon      (lon) float32 200.0 202.5 205.0 207.5 ... 322.5 325.0 327.5 330.0
  * time     (time) datetime64[ns] 2013-01-01 ... 2014-12-31T18:00:00
Attributes:
    long_name:     4xDaily Air temperature at sigma level 995
    units:         degK
    precision:     2
    GRIB_id:       11
    GRIB_name:     TMP
    var_desc:      Air temperature
    dataset:       NMC Reanalysis
    level_desc:    Surface
    statistic:     Individual Obs
    parent_stat:   Other
    actual_range:  [185.16 322.1 ]

In [14]:
ds.air.attrs

{'long_name': '4xDaily Air temperature at sigma level 995',
 'units': 'degK',
 'precision': 2,
 'GRIB_id': 11,
 'GRIB_name': 'TMP',
 'var_desc': 'Air temperature',
 'dataset': 'NMC Reanalysis',
 'level_desc': 'Surface',
 'statistic': 'Individual Obs',
 'parent_stat': 'Other',
 'actual_range': array([185.16, 322.1 ], dtype=float32)}

In [15]:
ds

<xarray.Dataset>
Dimensions:  (lat: 25, time: 2920, lon: 53)
Coordinates:
  * lat      (lat) float32 75.0 72.5 70.0 67.5 65.0 ... 25.0 22.5 20.0 17.5 15.0
  * lon      (lon) float32 200.0 202.5 205.0 207.5 ... 322.5 325.0 327.5 330.0
  * time     (time) datetime64[ns] 2013-01-01 ... 2014-12-31T18:00:00
Data variables:
    air      (time, lat, lon) float32 241.2 242.5 243.5 ... 296.5 296.2 295.7
Attributes:
    Conventions:  COARDS
    title:        4x daily NMC reanalysis (1948)
    description:  Data is from NMC initialized reanalysis\n(4x/day).  These a...
    platform:     Model
    references:   http://www.esrl.noaa.gov/psd/data/gridded/data.ncep.reanaly...

In [16]:
# assign your own attributes!
ds.air.attrs["who_is_awesome"] = "xarray"
ds.air.attrs

{'long_name': '4xDaily Air temperature at sigma level 995',
 'units': 'degK',
 'precision': 2,
 'GRIB_id': 11,
 'GRIB_name': 'TMP',
 'var_desc': 'Air temperature',
 'dataset': 'NMC Reanalysis',
 'level_desc': 'Surface',
 'statistic': 'Individual Obs',
 'parent_stat': 'Other',
 'actual_range': array([185.16, 322.1 ], dtype=float32),
 'who_is_awesome': 'xarray'}

**Note** that the attributes can be specified for each level (i.e. DataSet as well as a single DataArray)

In [17]:
ds

<xarray.Dataset>
Dimensions:  (lat: 25, time: 2920, lon: 53)
Coordinates:
  * lat      (lat) float32 75.0 72.5 70.0 67.5 65.0 ... 25.0 22.5 20.0 17.5 15.0
  * lon      (lon) float32 200.0 202.5 205.0 207.5 ... 322.5 325.0 327.5 330.0
  * time     (time) datetime64[ns] 2013-01-01 ... 2014-12-31T18:00:00
Data variables:
    air      (time, lat, lon) float32 241.2 242.5 243.5 ... 296.5 296.2 295.7
Attributes:
    Conventions:  COARDS
    title:        4x daily NMC reanalysis (1948)
    description:  Data is from NMC initialized reanalysis\n(4x/day).  These a...
    platform:     Model
    references:   http://www.esrl.noaa.gov/psd/data/gridded/data.ncep.reanaly...

In [18]:
ds.air

<xarray.DataArray 'air' (time: 2920, lat: 25, lon: 53)>
array([[[241.2    , 242.5    , 243.5    , ..., 232.79999, 235.5    ,
         238.59999],
        [243.79999, 244.5    , 244.7    , ..., 232.79999, 235.29999,
         239.29999],
        [250.     , 249.79999, 248.89   , ..., 233.2    , 236.39   ,
         241.7    ],
        ...,
        [296.6    , 296.19998, 296.4    , ..., 295.4    , 295.1    ,
         294.69998],
        [295.9    , 296.19998, 296.79   , ..., 295.9    , 295.9    ,
         295.19998],
        [296.29   , 296.79   , 297.1    , ..., 296.9    , 296.79   ,
         296.6    ]],

       [[242.09999, 242.7    , 243.09999, ..., 232.     , 233.59999,
         235.79999],
        [243.59999, 244.09999, 244.2    , ..., 231.     , 232.5    ,
         235.7    ],
        [253.2    , 252.89   , 252.09999, ..., 230.79999, 233.39   ,
         238.5    ],
...
        [293.69   , 293.88998, 295.38998, ..., 295.09   , 294.69   ,
         294.29   ],
        [296.29   , 297.19   , 297.59   , ..., 295.29   , 295.09   ,
         294.38998],
        [297.79   , 298.38998, 298.49   , ..., 295.69   , 295.49   ,
         295.19   ]],

       [[245.09   , 244.29   , 243.29   , ..., 241.68999, 241.48999,
         241.79   ],
        [249.89   , 249.29   , 248.39   , ..., 239.59   , 240.29   ,
         241.68999],
        [262.99   , 262.19   , 261.38998, ..., 239.89   , 242.59   ,
         246.29   ],
        ...,
        [293.79   , 293.69   , 295.09   , ..., 295.29   , 295.09   ,
         294.69   ],
        [296.09   , 296.88998, 297.19   , ..., 295.69   , 295.69   ,
         295.19   ],
        [297.69   , 298.09   , 298.09   , ..., 296.49   , 296.19   ,
         295.69   ]]], dtype=float32)
Coordinates:
  * lat      (lat) float32 75.0 72.5 70.0 67.5 65.0 ... 25.0 22.5 20.0 17.5 15.0
  * lon      (lon) float32 200.0 202.5 205.0 207.5 ... 322.5 325.0 327.5 330.0
  * time     (time) datetime64[ns] 2013-01-01 ... 2014-12-31T18:00:00
Attributes:
    long_name:       4xDaily Air temperature at sigma level 995
    units:           degK
    precision:       2
    GRIB_id:         11
    GRIB_name:       TMP
    var_desc:        Air temperature
    dataset:         NMC Reanalysis
    level_desc:      Surface
    statistic:       Individual Obs
    parent_stat:     Other
    actual_range:    [185.16 322.1 ]
    who_is_awesome:  xarray

## Create a DataSet

Let us create a dummy xarray Dataset for the following scenario: we have a three variables (DataArray):
- experimental timing event: `stimulus_onset` -> a single value per trial
- behavioral variable: `running_speed` -> a 1d array per trial where each element corresponds to the speed at a specific time
- neural activity: `population_response` -> a 2d array per trial where each row column is the activity of a single neuron over time

In [19]:
from xarray import Dataset, DataArray

In [20]:
import pandas as pd
start_time = '2023-01-01 00:00:00'
end_time = pd.Timestamp(start_time) + pd.Timedelta(seconds=2.5)
time_points = pd.date_range(start=start_time, end=end_time, freq='10L')[:-1]

In [21]:
np.random.seed(42)

trial_indices = np.arange(200)
timepoints = time_points.values
neuron_indices = np.arange(500)

stimulus_onset = np.random.rand(len(trial_indices))
running_speed = np.random.rand(len(trial_indices), len(time_points))
population_response = np.random.rand(len(trial_indices), len(time_points), len(neuron_indices))

ds = Dataset(
    data_vars= dict(
        stimulus_onset=DataArray(
            data=stimulus_onset,
        ),
        running_speed=DataArray(
            data=running_speed,
        ),
        population_response=DataArray(
            data=population_response,
        ),
    ),
    coords= dict(
        trial_indices=trial_indices,
        time_points=timepoints,
        neuron_indices=neuron_indices,
    )
)

In [22]:
ds.sel(trial_indices=slice(2, 5))

<xarray.Dataset>
Dimensions:              (dim_0: 200, dim_1: 250, dim_2: 500, trial_indices: 4,
                          time_points: 250, neuron_indices: 500)
Coordinates:
  * trial_indices        (trial_indices) int64 2 3 4 5
  * time_points          (time_points) datetime64[ns] 2023-01-01 ... 2023-01-...
  * neuron_indices       (neuron_indices) int64 0 1 2 3 4 ... 496 497 498 499
Dimensions without coordinates: dim_0, dim_1, dim_2
Data variables:
    stimulus_onset       (dim_0) float64 0.3745 0.9507 0.732 ... 0.8871 0.7799
    running_speed        (dim_0, dim_1) float64 0.642 0.08414 ... 0.696 0.2608
    population_response  (dim_0, dim_1, dim_2) float64 0.001483 ... 0.3423

In [23]:
ds.stimulus_onset.shape

(200,)

In [24]:
ds.sel(trial_indices=slice(2, 5)).stimulus_onset.shape

(200,)

In [25]:
np.random.seed(42)

trial_indices = np.arange(200)
timepoints = time_points.values
neuron_indices = np.arange(500)

stimulus_onset = np.random.rand(len(trial_indices))
running_speed = np.random.rand(len(trial_indices), len(time_points))
population_response = np.random.rand(len(trial_indices), len(time_points), len(neuron_indices))

ds = Dataset(
    data_vars= dict(
        stimulus_onset=DataArray(
            data=stimulus_onset,
            coords=dict(
                trial_indices=trial_indices,
            )
        ),
        running_speed=DataArray(
            data=running_speed,
        ),
        population_response=DataArray(
            data=population_response,
        ),
    ),
    coords= dict(
        trial_indices=trial_indices,
        time_points=timepoints,
        neuron_indices=neuron_indices,
    )
)

In [26]:
ds.sel(trial_indices=slice(2, 5))

<xarray.Dataset>
Dimensions:              (trial_indices: 4, dim_0: 200, dim_1: 250, dim_2: 500,
                          time_points: 250, neuron_indices: 500)
Coordinates:
  * trial_indices        (trial_indices) int64 2 3 4 5
  * time_points          (time_points) datetime64[ns] 2023-01-01 ... 2023-01-...
  * neuron_indices       (neuron_indices) int64 0 1 2 3 4 ... 496 497 498 499
Dimensions without coordinates: dim_0, dim_1, dim_2
Data variables:
    stimulus_onset       (trial_indices) float64 0.732 0.5987 0.156 0.156
    running_speed        (dim_0, dim_1) float64 0.642 0.08414 ... 0.696 0.2608
    population_response  (dim_0, dim_1, dim_2) float64 0.001483 ... 0.3423

In [27]:
ds.stimulus_onset.shape

(200,)

In [28]:
ds.sel(trial_indices=slice(2, 5)).stimulus_onset.shape

(4,)

In [29]:
ds.running_speed.shape

(200, 250)

In [30]:
ds.sel(trial_indices=slice(2, 5)).running_speed.shape

(200, 250)

In [31]:
np.random.seed(42)

trial_indices = np.arange(200)
timepoints = time_points.values
neuron_indices = np.arange(500)

stimulus_onset = np.random.rand(len(trial_indices))
running_speed = np.random.rand(len(trial_indices), len(time_points))
population_response = np.random.rand(len(trial_indices), len(time_points), len(neuron_indices))

ds = Dataset(
    data_vars= dict(
        stimulus_onset=DataArray(
            data=stimulus_onset,
            coords=dict(
                trial_indices=trial_indices,
            )
        ),
        running_speed=DataArray(
            data=running_speed,
            coords=dict(
                trial_indices=trial_indices,
                time_points=timepoints,
            )
        ),
        population_response=DataArray(
            data=population_response,
        ),
    ),
    coords= dict(
        trial_indices=trial_indices,
        time_points=timepoints,
        neuron_indices=neuron_indices,
    )
)

In [32]:
ds.sel(trial_indices=slice(2, 5)).running_speed.shape

(4, 250)

In [33]:
timepoints[-1]

numpy.datetime64('2023-01-01T00:00:02.490000000')

In [34]:
from datetime import datetime
timestamp = datetime(year=2023, month=1, day=1, hour=0, minute=0, second=0, microsecond=100000)

In [35]:
ds.sel(trial_indices=slice(2, 5), time_points=time_points<timestamp).running_speed.shape

(4, 10)

In [36]:
ds.sel(trial_indices=slice(2, 5), time_points=time_points<timestamp).population_response.shape

(200, 250, 500)

In [37]:
np.random.seed(42)

trial_indices = np.arange(200)
timepoints = time_points.values
neuron_indices = np.arange(500)

stimulus_onset = np.random.rand(len(trial_indices))
running_speed = np.random.rand(len(trial_indices), len(time_points))
population_response = np.random.rand(len(trial_indices), len(time_points), len(neuron_indices))

ds = Dataset(
    data_vars= dict(
        stimulus_onset=DataArray(
            data=stimulus_onset,
            coords=dict(
                trial_indices=trial_indices,
            )
        ),
        running_speed=DataArray(
            data=running_speed,
            coords=dict(
                trial_indices=trial_indices,
                time_points=timepoints,
            )
        ),
        population_response=DataArray(
            data=population_response,
            coords=dict(
                trial_indices=trial_indices,
                time_points=timepoints,
                neuron_indices=neuron_indices,
            )
        ),
    ),
    coords= dict(
        trial_indices=trial_indices,
        time_points=timepoints,
        neuron_indices=neuron_indices,
    )
)

In [38]:
ds.sel(trial_indices=slice(2, 5), time_points=time_points<timestamp).population_response.shape

(4, 10, 500)

### Alternative 1 (shorter)

In [39]:
np.random.seed(42)

trial_indices = np.arange(200)
timepoints = time_points.values
neuron_indices = np.arange(500)

stimulus_onset = np.random.rand(len(trial_indices))
running_speed = np.random.rand(len(trial_indices), len(time_points))
population_response = np.random.rand(len(trial_indices), len(time_points), len(neuron_indices))

ds = Dataset(
    data_vars= dict(
        stimulus_onset=DataArray(
            data=stimulus_onset,
            dims=("trial_indices")
        ),
        running_speed=DataArray(
            data=running_speed,
            dims=("trial_indices", "time_points")
        ),
        population_response=DataArray(
            data=population_response,
            dims=("trial_indices", "time_points", "neuron_indices")
        ),
    ),
    coords= dict(
        trial_indices=trial_indices,
        time_points=timepoints,
        neuron_indices=neuron_indices,
    )
)

In [40]:
ds

<xarray.Dataset>
Dimensions:              (trial_indices: 200, time_points: 250,
                          neuron_indices: 500)
Coordinates:
  * trial_indices        (trial_indices) int64 0 1 2 3 4 ... 195 196 197 198 199
  * time_points          (time_points) datetime64[ns] 2023-01-01 ... 2023-01-...
  * neuron_indices       (neuron_indices) int64 0 1 2 3 4 ... 496 497 498 499
Data variables:
    stimulus_onset       (trial_indices) float64 0.3745 0.9507 ... 0.8871 0.7799
    running_speed        (trial_indices, time_points) float64 0.642 ... 0.2608
    population_response  (trial_indices, time_points, neuron_indices) float64 ...

In [41]:
ds.sel(trial_indices=slice(2, 5)).stimulus_onset.shape

(4,)

In [42]:
ds.sel(trial_indices=slice(2, 5), time_points=time_points<timestamp).running_speed.shape

(4, 10)

In [43]:
ds.sel(trial_indices=slice(2, 5), time_points=time_points<timestamp).population_response.shape

(4, 10, 500)

In [44]:
ds.sel(trial_indices=slice(2, 5), time_points=time_points<timestamp).stimulus_onset.shape

(4,)

### Alternative 2 (shortest)

In [45]:
ds = Dataset(
    data_vars= dict(
        # var_name = (dims, data)
        stimulus_onset=(("trial_indices"), stimulus_onset),
        running_speed=(("trial_indices", "time_points"), running_speed),
        population_response=(("trial_indices", "time_points", "neuron_indices"), population_response)
    ),
    coords= dict(
        trial_indices=trial_indices,
        time_points=timepoints,
        neuron_indices=neuron_indices,
    )
)

In [46]:
ds

<xarray.Dataset>
Dimensions:              (trial_indices: 200, time_points: 250,
                          neuron_indices: 500)
Coordinates:
  * trial_indices        (trial_indices) int64 0 1 2 3 4 ... 195 196 197 198 199
  * time_points          (time_points) datetime64[ns] 2023-01-01 ... 2023-01-...
  * neuron_indices       (neuron_indices) int64 0 1 2 3 4 ... 496 497 498 499
Data variables:
    stimulus_onset       (trial_indices) float64 0.3745 0.9507 ... 0.8871 0.7799
    running_speed        (trial_indices, time_points) float64 0.642 ... 0.2608
    population_response  (trial_indices, time_points, neuron_indices) float64 ...

In [47]:
ds.sel(trial_indices=slice(2, 5)).stimulus_onset.shape

(4,)

In [48]:
ds.sel(trial_indices=slice(2, 5), time_points=time_points<timestamp).running_speed.shape

(4, 10)

In [49]:
ds.sel(trial_indices=slice(2, 5), time_points=time_points<timestamp).population_response.shape

(4, 10, 500)

In [50]:
ds.sel(trial_indices=slice(2, 5), time_points=time_points<timestamp).stimulus_onset.shape

(4,)

## Save as NetCDF file

In [51]:
ds.to_netcdf('my_data.nc')

## Load a NetCDF file

In [52]:
xr.open_dataset('my_data.nc')

<xarray.Dataset>
Dimensions:              (trial_indices: 200, time_points: 250,
                          neuron_indices: 500)
Coordinates:
  * trial_indices        (trial_indices) int64 0 1 2 3 4 ... 195 196 197 198 199
  * time_points          (time_points) datetime64[ns] 2023-01-01 ... 2023-01-...
  * neuron_indices       (neuron_indices) int64 0 1 2 3 4 ... 496 497 498 499
Data variables:
    stimulus_onset       (trial_indices) float64 ...
    running_speed        (trial_indices, time_points) float64 ...
    population_response  (trial_indices, time_points, neuron_indices) float64 ...